version: '3.4'
services:
    omnicola:
      build: .
      ports:
        - "9292:9292"
      environment:
        DATABASE_URL: postgres://postgres@omnicola.postgres:5432/omnicola 
      container_name: omnicola.app
      tty: true
      networks:
        - omnicola
      volumes:
        - .:/app/

    postgresql:
      build:
        context: ./postgres/
      container_name: omnicola.postgres
      ports:
        - "5434:5432"
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_DB: omnicola_test
      volumes:
      - postgres-data:/var/lib/postgresql/data/
      networks:
      - omnicola

volumes:
  postgres-data:

networks:
  omnicola:
