version: '3.4'
services:
    postgresql:
      build:
        context: ./postgres/
      container_name: omnicola.postgres
      ports:
        - "5434:5432"
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_DB: omnicola_test
      volumes:
      - postgres-data:/var/lib/postgresql/data/
      networks:
      - omnicola

volumes:
  postgres-data:

networks:
  omnicola:
